### ISSUE TITLE
タスクと課題を棚卸する

### ISSUE THREAD

**Issue by uns-miyama** [uns-miyama/uns-tech-lab#3]
### 作業内容

- Raspberry Piチーム、iOSアプリチーム双方のタスクと課題を洗い出す

### 理由

- タスク・課題が明確でないため、プロジェクト自体が滞っているため

**Comment by Fujiki-Hiroshi** [comment]
iOSチームのタスク洗い出しは
#7 を参照してください。

**Comment by uns-miyama** [comment]
完了とみなしクローズ
