### ISSUE TITLE
iOS タスクの洗い出し

### ISSUE THREAD

**Issue by Fujiki-Hiroshi** [uns-miyama/uns-tech-lab#7]

**Comment by Fujiki-Hiroshi** [comment]
# ２月末対応予定
# ３月以降対応予定


_元ネタ_　URL(1/26 作成）
_https://docs.google.com/spreadsheets/d/1K4Y0orB9WWxrFEYXlrS1rU-LKj51KZ9Xf1BVJq2WFRk/edit?usp=sharing_

**Comment by uns-miyama** [comment]
@Fujiki-Hiroshi この手のIssueは、クローズせずに、オープンのままにしておいた方が良いです

内容については、Markdownで綺麗に書かれていますし、良いのではないでしょうか 😄
